---
- name: DNF Update
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check if reboot is required after update
  ansible.builtin.command: "dnf needs-restarting -r"
  register: reboot_required
  failed_when: false
  check_mode: false
  changed_when: false

- name: Notify that a reboot is required after update
  ansible.builtin.debug:
    msg: "WARNING: A reboot is required after the DNF update. Please restart the system manually."
  when: reboot_required.rc == 1

- name: Software install
  ansible.builtin.dnf:
    name:
      - fish
      - fastfetch
      - micro
      - restic
      - bat
      - lm_sensors
      - podman
      - cockpit
      - cockpit-storaged
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-selinux
      #- cockpit-sosreport
      #- cockpit-files
      - rsync
      - nut
      - prometheus-podman-exporter
    state: present

- name: Upload lm_sensors config
  ansible.builtin.copy:
    src: "lm_sensors/lm_sensors"
    dest: "/etc/sysconfig/lm_sensors"
    owner: root
    group: root
    mode: '0644'
  notify: Restart lm_sensors

# Default: false
- name: Allow containers to use host hardware devices (SELinux)
  ansible.posix.seboolean:
    name: container_use_devices
    state: true
    persistent: true

# Default: 2
- name: Allow unpriviledged users to read hardware performance counters
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
