---
- name: Stop and disable ModemManager
  ansible.builtin.systemd:
    name: ModemManager.service
    state: stopped
    enabled: false
    masked: true

# TODO
# cockpit-sosreport
# cockpit-files
- name: Software install
  ansible.builtin.dnf:
    name:
      - fish
      - fastfetch
      - micro
      - restic
      - bat
      - lm_sensors
      - cockpit
      - cockpit-storaged
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-selinux
      - rsync
      - rclone
      - nut
      - fail2ban
      - python3
      - git
    state: present

- name: Upload lm_sensors config
  ansible.builtin.copy:
    src: "lm_sensors/lm_sensors"
    dest: "/etc/sysconfig/lm_sensors"
    owner: root
    group: root
    mode: "0644"
  notify: Restart lm_sensors

# Default: 2
- name: Allow unpriviledged users to read hardware performance counters
  ansible.posix.sysctl:
    name: kernel.perf_event_paranoid
    value: "0"
    sysctl_set: true
    state: present
    reload: true

# https://docs.kernel.org/hwmon/nct6683.html
- name: Load nct6683 module and make it persistent
  community.general.modprobe:
    name: nct6683
    params: "force=1"
    state: present
    persistent: present
