---
- name: Verify OpenRGB build directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/openrgb/openrgb-build"

- name: Upload Containerfile
  ansible.builtin.template:
    src: "Containerfile.j2"
    dest: "{{ stacks_path }}/openrgb/openrgb-build/Containerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  register: openrgb_containerfile

- name: Build OpenRGB image
  containers.podman.podman_image:
    name: custom-openrgb
    tag: "latest"
    path: "{{ stacks_path }}/openrgb/openrgb-build"
    force: "{{ openrgb_containerfile is changed }}"
  register: openrgb_image

- name: Deploy OpenRGB
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: openrgb
    podman_service_dirs:
      - "{{ stacks_path }}/openrgb"
    podman_service_quadlets: ["openrgb.container"]
    podman_service_changed_extra: "{{ (openrgb_containerfile is changed) or (openrgb_image is changed) }}"
