---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/openrgb"
    - "{{ stacks_path }}/openrgb/openrgb-build"

- name: Upload .container file
  ansible.builtin.template:
    src: "openrgb.container.j2"
    dest: "{{ quadlet_path }}/openrgb.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart openrgb

- name: Upload Containerfile
  ansible.builtin.template:
    src: "Containerfile.j2"
    dest: "{{ stacks_path }}/openrgb/openrgb-build/Containerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  register: openrgb_containerfile

- name: Build image
  containers.podman.podman_image:
    name: custom-openrgb
    tag: "latest"
    path: "{{ stacks_path }}/openrgb/openrgb-build"
    force: "{{ openrgb_containerfile.changed }}"
  notify: Restart openrgb

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: openrgb.service
    state: started
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"
