FROM {{ caddy_image }}:{{ version_caddy }}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM {{ caddy_image }}:{{ version_caddy }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
