---
homelab_user: "{{ ansible_user }}"
user_home: "/home/{{ homelab_user }}"
stacks_path: "{{ user_home }}/stacks"
quadlet_path: "{{ user_home }}/.config/containers/systemd"
user_units_path: "{{ user_home }}/.config/systemd/user"
user_bin_path: "{{ user_home }}/.local/bin"
monitoring_path: "/srv/monitoring"
immich_path: "/srv/immich"
backup_mount: "/mnt/backup"
frigate_mount: "/mnt/frigate"
alloy_metrics_directory: "/opt/alloy-metrics"
git_backup_dir: "{{ user_home }}/backups/git_repos"
podman_user_env:
  XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
