---
podman_unprivileged_port_start: 53

podman_networks:
  - { name: home, internal: true }
  - { name: monitoring-backend, internal: true }
  - { name: authelia }
  - { name: frigate }
  - { name: grafana }
  - { name: homeassistant }
  - { name: homepage }
  - { name: immich }
  - { name: loki }
  - { name: peanut }
  - { name: prometheus }
  - { name: vaultwarden }
  - { name: zigbee2mqtt }
  - { name: authelia-backend, internal: true }
  - { name: immich-backend, internal: true }
  - { name: openrgb, internal: true }
  - { name: restic, internal: true }
