---
stacks_path: "/home/{{ ansible_user }}/stacks"

timezone: "Europe/Warsaw"

services:
  files:
    subdomain: "files"
  alloy:
    subdomain: "alloy"
  authelia:
    subdomain: "auth"
  authelia_postgres:
    quadlet_name: "authelia-postgres.service"
  authelia_redis:
    quadlet_name: "authelia-redis.service"
  frigate:
    subdomain: "frigate"
  grafana:
    subdomain: "grafana"
  pihole:
    subdomain: "pihole"
  prometheus:
    subdomain: "prometheus"
  loki:
    subdomain: "logs"
  restic:
    subdomain: "backup"
  immich:
    subdomain: "immich"
  vaultwarden:
    subdomain: "vault"
    quadlet_name: "vaultwarden"
    backup:
      stop: true
      paths:
        - /home/{{ ansible_user }}/stacks/vaultwarden/data
      excludes:
        - /home/{{ ansible_user }}/stacks/vaultwarden/data/icon_cache
  go2rtc:
    subdomain: "go2rtc"
  zigbee2mqtt:
    subdomain: "z2m"
    quadlet_name: "zigbee2mqtt"
    backup:
      stop: true
      paths:
        - /home/{{ ansible_user }}/stacks/zigbee2mqtt/data
  homeassistant:
    subdomain: "ha"
    quadlet_name: "homeassistant"
    backup:
      stop: true
      paths:
        - /home/{{ ansible_user }}/stacks/homeassistant/config/backups
  uptime_kuma:
    subdomain: "kuma"
  peanut:
    subdomain: "peanut"
  cockpit:
    subdomain: "cockpit"
  switch:
    subdomain: "switch"
  mainsail:
    subdomain: "mainsail"
  camera_doorbell:
    subdomain: "camera-doorbell"
  camera_front:
    subdomain: "camera-front"
  camera_back:
    subdomain: "camera-back"
  camera_entry:
    subdomain: "camera-entry"
