---
timezone: "Europe/Warsaw"

git_backup_repos:
  - name: "nova-homelab.git"
    url: "https://github.com/Zireaell1/nova-homelab.git"
  - name: "nova-eink-display.git"
    url: "https://github.com/Zireaell1/nova-eink-display.git"

services:
  files:
    subdomain: "files"
  alloy:
    subdomain: "alloy"
  authelia:
    subdomain: "auth"
  frigate:
    subdomain: "frigate"
    backup:
      stop: false
      paths:
        - "{{ frigate_mount }}/storage/exports"
  grafana:
    subdomain: "grafana"
  pihole:
    subdomain: "pihole"
  prometheus:
    subdomain: "prometheus"
  loki:
    subdomain: "logs"
  restic:
    subdomain: "backup"
    backup:
      stop: false
      paths:
        - "{{ git_backup_dir }}"
  immich:
    subdomain: "immich"
  vaultwarden:
    subdomain: "vault"
    backup:
      stop: true
      paths:
        - "{{ stacks_path }}/vaultwarden/data"
      excludes:
        - "{{ stacks_path }}/vaultwarden/data/icon_cache"
  go2rtc:
    subdomain: "go2rtc"
  zigbee2mqtt:
    subdomain: "z2m"
    backup:
      stop: true
      paths:
        - "{{ stacks_path }}/zigbee2mqtt/data"
        - "{{ stacks_path }}/zigbee2mqtt/config/devices.yaml"
        - "{{ stacks_path }}/zigbee2mqtt/config/groups.yaml"
  homeassistant:
    subdomain: "ha"
    backup:
      stop: false
      paths:
        - "{{ stacks_path }}/homeassistant/config/backups"
  peanut:
    subdomain: "peanut"
  cockpit:
    subdomain: "cockpit"
  switch:
    subdomain: "switch"
  mainsail:
    subdomain: "mainsail"
  camera_doorbell:
    subdomain: "camera-doorbell"
  camera_front:
    subdomain: "camera-front"
  camera_back:
    subdomain: "camera-back"
  camera_entry:
    subdomain: "camera-entry"
