---
stacks_path: "/home/{{ ansible_user }}/stacks"

zellij_version: "0.43.1"

user_shell: "/usr/bin/fish"

data_drives:
  - uuid: "3ddf5ac7-b3a8-4ac2-8573-f38c02297c04"
    fstype: "xfs"
    mountpoint: "/mnt/backup"
    passno: "0"
  - uuid: "cb64996e-45e2-4806-b8b1-f14635ecaa2f"
    fstype: "xfs"
    mountpoint: "/mnt/frigate"
    passno: "0"

timezone: "Europe/Warsaw"

services:
  alloy:
    subdomain: "alloy"
  authelia:
    subdomain: "auth"
  authelia_postgres:
    quadlet_name: "authelia-postgres.service"
  authelia_redis:
    quadlet_name: "authelia-redis.service"
  frigate:
    subdomain: "frigate"
  grafana:
    subdomain: "grafana"
  pihole:
    subdomain: "pihole"
  prometheus:
    subdomain: "prometheus"
  loki:
    subdomain: "logs"
  restic:
    subdomain: "backup"
  immich:
    subdomain: "immich"
  vaultwarden:
    subdomain: "vault"
    quadlet_name: "vaultwarden"
    backup:
      stop: true
      paths:
        - /home/{{ ansible_user }}/stacks/vaultwarden/data
      excludes:
        - /home/{{ ansible_user }}/stacks/vaultwarden/data/icon_cache
  go2rtc:
    subdomain: "go2rtc"
  zigbee2mqtt:
    subdomain: "z2m"
  homeassistant:
    subdomain: "ha"
  uptime_kuma:
    subdomain: "kuma"
  peanut:
    subdomain: "peanut"
  cockpit:
    subdomain: "cockpit"
  switch:
    subdomain: "switch"
  mainsail:
    subdomain: "mainsail"
  camera_doorbell:
    subdomain: "camera-doorbell"
  camera_front:
    subdomain: "camera-front"
  camera_back:
    subdomain: "camera-back"
  camera_entry:
    subdomain: "camera-entry"

ip: "192.168.3.2"
secondary_ip: "10.10.10.1/24"

network_tailscale: "100.64.0.0/10"
network_home: "192.168.2.0/24"
network_homelab: "192.168.3.0/24"
network_iot: "192.168.4.0/24"
network_cctv: "10.10.10.0/24"

secondary_network_interface_name: "enp2s0"

dashboard_tablet_ip: "192.168.4.10"

printer_ip: "192.168.2.9:4409"

switch_ip: "10.10.10.2:80"

camera_doorbell_http_ip: "10.10.10.10:80"
camera_doorbell_rtsp_ip: "10.10.10.10:554"
camera_front_http_ip: "10.10.10.11:80"
camera_front_rtsp_ip: "10.10.10.11:554"
camera_back_http_ip: "10.10.10.12:80"
camera_back_rtsp_ip: "10.10.10.12:554"
camera_entry_http_ip: "10.10.10.13:80"
camera_entry_rtsp_ip: "10.10.10.13:554"

vg_name: "fedora_nova-2"

target_lvs:
  - name: root
    size: 15g
    manage_fs_and_mount: false
  - name: home
    size: 50g
    mount_path: /home
    manage_fs_and_mount: true
  - name: monitoring
    size: 10g
    mount_path: /srv/monitoring
    manage_fs_and_mount: true
  - name: immich
    size: 50g
    mount_path: /srv/immich
    manage_fs_and_mount: true
