# Authelia

# renovate: datasource=docker depName=docker.io/authelia/authelia
version_authelia: "4.39.19"

# renovate: datasource=docker depName=docker.io/library/redis
version_authelia_redis: "8.6.3"

# renovate: datasource=docker depName=docker.io/library/postgres
version_authelia_postgres: "18.3"

# Caddy

# renovate: datasource=docker depName=docker.io/library/caddy
version_caddy: "2.11.3"

# Frigate

# renovate: datasource=docker depName=ghcr.io/blakeblackshear/frigate
version_frigate: "0.17.1"

# Grafana

# renovate: datasource=docker depName=docker.io/grafana/grafana
version_grafana: "13.0.1"

# Immich

# renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
version_immich: "v3.0.3"

# renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
version_immich_machine_learning: "v3.0.3"

# renovate: datasource=docker depName=docker.io/valkey/valkey
version_immich_redis: "9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9"

# renovate: datasource=docker depName=ghcr.io/immich-app/postgres
version_immich_postgres: "14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23"

# Loki

# renovate: datasource=docker depName=docker.io/grafana/loki
version_loki: "3.7.1"

# Mosquitto

# renovate: datasource=docker depName=docker.io/library/eclipse-mosquitto
version_mosquitto: "2.1.2-alpine"

# Peanut

# renovate: datasource=docker depName=docker.io/brandawg93/peanut
version_peanut: "6.0.0"

# Pi-Hole

# renovate: datasource=docker depName=docker.io/pihole/pihole
version_pihole: "2026.05.0"

# Prometheus

# renovate: datasource=docker depName=docker.io/prom/prometheus
version_prometheus: "v3.11.3-distroless"

# Restic (Rest server)

# renovate: datasource=docker depName=docker.io/restic/rest-server
version_restic: "0.14.0"

# Vaultwarden

# renovate: datasource=docker depName=ghcr.io/dani-garcia/vaultwarden
version_vaultwarden: "1.36.0"

# Zigbee2MQTT

# renovate: datasource=docker depName=ghcr.io/koenkk/zigbee2mqtt
version_zigbee2mqtt: "2.10.1"

# HomeAssistant

# renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant
version_homeassistant: "2026.6.3"

# renovate: datasource=github-releases depName=hacs/integration
version_hacs: "2.0.5"

# Homepage

# renovate: datasource=docker depName=ghcr.io/gethomepage/homepage
version_homepage: "v1.13.2"
