---
nut_exporter_memory_limit: "500m"

# https://github.com/DRuggeri/nut_exporter
nut_exporter_image: "ghcr.io/druggeri/nut_exporter"

# renovate: datasource=docker depName=ghcr.io/druggeri/nut_exporter
nut_exporter_version: "3.3.0"

nut_exporter_nut_user: "ups_exporter"
