---
- name: Reload Udev rules
  ansible.builtin.command:
    argv: [udevadm, control, --reload-rules]
  changed_when: true

- name: Retrigger rgb devices
  ansible.builtin.command:
    argv: [udevadm, trigger, --subsystem-match=hidraw, --action=change]
  changed_when: true

- name: Restart fwupd
  ansible.builtin.service:
    name: fwupd.service
    state: restarted
