---
- name: Software install
  ansible.builtin.dnf:
    name: nut
    state: present

- name: Configure standard NUT files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/ups/{{ item }}"
    owner: "root"
    group: "nut"
    mode: "0640"
    backup: true
  loop:
    - nut.conf
    - ups.conf
    - upsd.conf
    - upsmon.conf
  notify:
    - Restart NUT enumerator
    - Restart NUT server
    - Restart NUT monitor

- name: Configure upsd.users (Server Credentials)
  ansible.builtin.template:
    src: "upsd.users.j2"
    dest: "/etc/ups/upsd.users"
    owner: "root"
    group: "nut"
    mode: "0640"
    backup: true
  no_log: true
  notify:
    - Restart NUT enumerator
    - Restart NUT server
    - Restart NUT monitor

- name: Flush handlers to restart NUT stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure continuous NUT services are started and enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nut-driver-enumerator.path
    - nut-server.service
    - nut-monitor.service
    - nut.target
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure NUT enumerator service is enabled
  ansible.builtin.systemd:
    name: nut-driver-enumerator.service
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
