---
vaultwarden_memory_limit: "500m"

# https://github.com/dani-garcia/vaultwarden
vaultwarden_image: "ghcr.io/dani-garcia/vaultwarden"

# renovate: datasource=docker depName=ghcr.io/dani-garcia/vaultwarden
vaultwarden_version: "1.36.0"
