---
- name: Restart homepage
  ansible.builtin.systemd:
    daemon_reload: true
    name: homepage.service
    state: restarted
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"
