---
- name: Restart lm_sensors
  ansible.builtin.systemd:
    name: lm_sensors.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart fstrim timer
  ansible.builtin.systemd:
    name: fstrim.timer
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload Udev rules
  ansible.builtin.command:
    argv: [udevadm, control, --reload-rules]
  changed_when: true

- name: Retrigger rgb devices
  ansible.builtin.command:
    argv: [udevadm, trigger, --subsystem-match=hidraw, --action=change]
  changed_when: true
