---
grafana_memory_limit: "2g"

# https://hub.docker.com/r/grafana/grafana/
grafana_image: "docker.io/grafana/grafana"

grafana_prometheus_datasource_name: "prometheus-datasource"
grafana_loki_datasource_name: "loki-datasource"

# renovate: datasource=docker depName=docker.io/grafana/grafana
grafana_version: "13.1.2"
