---
- name: Deploy Peanut
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: peanut
    podman_service_dirs:
      - "{{ stacks_path }}/peanut"
      - "{{ stacks_path }}/peanut/config"
    podman_service_templates:
      - src: settings.yml.j2
        dest: "{{ stacks_path }}/peanut/config/settings.yml"
        mode: "0600"
        no_log: true
    podman_service_quadlets: ["peanut.container"]
    podman_service_images: ["{{ peanut_image }}:{{ peanut_version }}"]
