---
alloy_enable_smartmon: true

alloy_config_template: "config_nova.alloy.j2"

hardware_data_drives:
  - uuid: "3ddf5ac7-b3a8-4ac2-8573-f38c02297c04"
    fstype: "xfs"
    mountpoint: "{{ backup_mount }}"
    passno: "0"
    fstrim_notrim: true

  - uuid: "cb64996e-45e2-4806-b8b1-f14635ecaa2f"
    fstype: "xfs"
    mountpoint: "{{ frigate_mount }}"
    passno: "0"
    fstrim_notrim: true

hardware_target_lvs:
  - name: root
    size: 15g
    manage_fs_and_mount: false
  - name: home
    size: 50g
    mount_path: /home
    manage_fs_and_mount: true
  - name: monitoring
    size: 10g
    mount_path: "{{ monitoring_path }}"
    manage_fs_and_mount: true
  - name: immich
    size: 50g
    mount_path: "{{ immich_path }}"
    manage_fs_and_mount: true

hardware_vg_name: "fedora_nova-2"

zigbee2mqtt_adapter_path: "/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_348e0dcf501fef11abc857d0639e525b-if00-port0"

primary_network_interface_name: "enp129s0"
secondary_network_interface_name: "enp2s0"
