---
- name: Restart caddy
  ansible.builtin.systemd:
    daemon_reload: true
    name: caddy.service
    state: restarted
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Reload caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  ignore_errors: "{{ ansible_check_mode }}"
