---
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart podman-prune timer
  ansible.builtin.systemd:
    name: podman-prune.timer
    state: restarted
    daemon_reload: true
    scope: user
