---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/vaultwarden"
    - "{{ stacks_path }}/vaultwarden/data"

- name: Upload .network file
  ansible.builtin.template:
    src: "vaultwarden.network.j2"
    dest: "{{ quadlet_path }}/vaultwarden.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart vaultwarden

- name: Upload .env file
  ansible.builtin.template:
    src: "vaultwarden.env.j2"
    dest: "{{ stacks_path }}/vaultwarden/vaultwarden.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  notify: Restart vaultwarden

- name: Upload .container file
  ansible.builtin.template:
    src: "vaultwarden.container.j2"
    dest: "{{ quadlet_path }}/vaultwarden.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart vaultwarden

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ vaultwarden_image }}:{{ vaultwarden_version }}"
    state: present

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: vaultwarden.service
    state: started
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"
