---
- name: Deploy Vaultwarden
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: vaultwarden
    podman_service_dirs:
      - "{{ stacks_path }}/vaultwarden"
      - "{{ stacks_path }}/vaultwarden/data"
    podman_service_templates:
      - src: vaultwarden.env.j2
        dest: "{{ stacks_path }}/vaultwarden/vaultwarden.env"
        mode: "0644"
      - src: vaultwarden.secrets.env.j2
        dest: "{{ stacks_path }}/vaultwarden/vaultwarden.secrets.env"
        mode: "0600"
    podman_service_quadlets: ["vaultwarden.container"]
    podman_service_images: ["{{ vaultwarden_image }}:{{ vaultwarden_version }}"]
