---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/homeassistant"
    - "{{ stacks_path }}/homeassistant/config"
    - "{{ stacks_path }}/homeassistant/config/custom_components"
    - "{{ stacks_path }}/homeassistant/config/custom_components/hacs"
    - "{{ stacks_path }}/homeassistant/config/www"
    - "{{ stacks_path }}/homeassistant/config/blueprints"
    - "{{ stacks_path }}/homeassistant/config/ansible_managed"

- name: Ensure Caddy download directory exists for HA app
  ansible.builtin.file:
    path: "{{ stacks_path }}/caddy/srv/homeassistant"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Download Home Assistant Android App (Minimal)
  ansible.builtin.get_url:
    url: "https://github.com/home-assistant/android/releases/download/{{ homeassistant_android_version }}/app-minimal-release.apk"
    dest: "{{ stacks_path }}/caddy/srv/homeassistant/home-assistant-android-{{ homeassistant_android_version }}.apk"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Download and extract latest HACS release
  ansible.builtin.unarchive:
    src: https://github.com/hacs/integration/releases/download/{{ homeassistant_hacs_version }}/hacs.zip
    dest: "{{ stacks_path }}/homeassistant/config/custom_components/hacs"
    remote_src: true
    creates: "{{ stacks_path }}/homeassistant/config/custom_components/hacs/manifest.json"
  notify: Restart homeassistant

- name: Upload .network file
  ansible.builtin.template:
    src: "homeassistant.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/homeassistant.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homeassistant

- name: Ensure base UI files exist
  ansible.builtin.copy:
    content: ""
    dest: "{{ stacks_path }}/homeassistant/config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    force: false
  loop:
    - automations.yaml
    - scripts.yaml
    - scenes.yaml
  notify: Restart homeassistant

- name: Ensure Prometheus filter file exists
  ansible.builtin.template:
    src: "prometheus_filter.yaml.j2"
    dest: "{{ stacks_path }}/homeassistant/config/ansible_managed/prometheus_filter.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homeassistant

- name: Upload configuration.yaml file
  ansible.builtin.template:
    src: "configuration.yaml.j2"
    dest: "{{ stacks_path }}/homeassistant/config/configuration.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homeassistant

- name: Upload .container file
  ansible.builtin.template:
    src: "homeassistant.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/homeassistant.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homeassistant

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ homeassistant_image }}:{{ homeassistant_version }}"
    state: present

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: homeassistant.service
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  ignore_errors: "{{ ansible_check_mode }}"
