---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/homepage"
    - "{{ stacks_path }}/homepage/config"
    - "{{ stacks_path }}/homepage/assets"
    - "{{ frigate_mount }}/homepage_monitoring"
    - "{{ backup_mount }}/homepage_monitoring"

- name: Upload .network file
  ansible.builtin.template:
    src: "homepage.network.j2"
    dest: "{{ quadlet_path }}/homepage.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homepage

- name: Upload .env file
  ansible.builtin.template:
    src: "homepage.env.j2"
    dest: "{{ stacks_path }}/homepage/homepage.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  notify: Restart homepage

- name: Upload Homepage files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ stacks_path }}/homepage/config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - bookmarks.yaml
    - services.yaml
    - settings.yaml
    - widgets.yaml
  notify: Restart homepage

- name: Sync all assets
  ansible.posix.synchronize:
    src: "files/"
    dest: "{{ stacks_path }}/homepage/assets/"
    delete: true
    archive: true
    owner: false
    group: false
    rsync_opts:
      - "--chmod=D0755,F0644"
      - "--chown={{ ansible_user }}:{{ ansible_user }}"
  notify: Restart homepage

- name: Upload .container file
  ansible.builtin.template:
    src: "homepage.container.j2"
    dest: "{{ quadlet_path }}/homepage.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart homepage

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ homepage_image }}:{{ homepage_version }}"
    state: present

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: homepage.service
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  ignore_errors: "{{ ansible_check_mode }}"
