---
- name: Verify Homepage static directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/homepage/assets"

- name: Sync all assets
  ansible.posix.synchronize:
    src: "files/"
    dest: "{{ stacks_path }}/homepage/assets/"
    delete: true
    archive: true
    owner: false
    group: false
    rsync_opts:
      - "--chmod=D0755,F0644"
      - "--chown={{ ansible_user }}:{{ ansible_user }}"
  register: homepage_sync_assets

- name: Deploy Homepage
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: homepage
    podman_service_dirs:
      - "{{ stacks_path }}/homepage"
      - "{{ stacks_path }}/homepage/config"
      - "{{ stacks_path }}/homepage/assets"
      - "{{ frigate_mount }}/homepage_monitoring"
      - "{{ backup_mount }}/homepage_monitoring"
    podman_service_templates:
      - src: bookmarks.yaml.j2
        dest: "{{ stacks_path }}/homepage/config/bookmarks.yaml"
        mode: "0644"
      - src: services.yaml.j2
        dest: "{{ stacks_path }}/homepage/config/services.yaml"
        mode: "0644"
      - src: settings.yaml.j2
        dest: "{{ stacks_path }}/homepage/config/settings.yaml"
        mode: "0644"
      - src: widgets.yaml.j2
        dest: "{{ stacks_path }}/homepage/config/widgets.yaml"
        mode: "0644"
    podman_service_quadlets: ["homepage.container"]
    podman_service_images: ["{{ homepage_image }}:{{ homepage_version }}"]
    podman_service_changed_extra: "{{ homepage_sync_assets is changed }}"
