---
- name: Restart immich
  ansible.builtin.systemd:
    daemon_reload: true
    name: immich.service
    state: restarted
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart immich-postgres
  ansible.builtin.systemd:
    daemon_reload: true
    name: immich-postgres.service
    state: restarted
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart immich-redis
  ansible.builtin.systemd:
    daemon_reload: true
    name: immich-redis.service
    state: restarted
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart immich-machine-learning
  ansible.builtin.systemd:
    daemon_reload: true
    name: immich-machine-learning.service
    state: restarted
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"
