---
- name: Install system dependencies
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - python3-dev
      - python3-packaging
      - python3-debian
      - git
      - swig
      - liblgpio-dev
      - pipx
      - gpg
    state: present
    update_cache: true

- name: Verify if config directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ user_units_path }}"
      mode: "0755"

    - path: "{{ user_bin_path }}"
      mode: "0755"

- name: Enable lingering for current user
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user }}"
  args:
    creates: "/var/lib/systemd/linger/{{ ansible_user }}"

- name: Provide static DNS entries in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '.*\b{{ item }}\.{{ vault_domain }}$'
    line: "{{ vault_primary_ip }} {{ item }}.{{ vault_domain }}"
    state: present
  loop: "{{ rpi_base_static_hosts }}"

- name: Enable SPI interface
  ansible.builtin.lineinfile:
    path: /boot/firmware/config.txt
    regexp: "^#?dtparam=spi="
    line: "dtparam=spi=on"
    state: present
  notify: Abort playbook if SPI was just enabled (manual reboot required)
