---
- name: Stop and disable ModemManager
  ansible.builtin.systemd:
    name: ModemManager.service
    state: stopped
    enabled: false
    masked: true

# TODO
# cockpit-sosreport
# cockpit-files
- name: Software install
  ansible.builtin.dnf:
    name:
      - fish
      - fastfetch
      - micro
      - restic
      - bat
      - cockpit
      - cockpit-storaged
      - cockpit-networkmanager
      - cockpit-podman
      - cockpit-selinux
      - rsync
      - rclone
      - python3
      - git
    state: present

- name: Check current version of Zellij
  ansible.builtin.command: zellij --version
  register: system_base_zellij_cmd_output
  failed_when: false
  check_mode: false
  changed_when: false

- name: Install Zellij from GitHub repo
  ansible.builtin.unarchive:
    src: "{{ system_base_zellij_link }}"
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/zellij
    owner: root
    group: root
    mode: "0755"
  when: system_base_zellij_cmd_output.rc != 0 or system_base_zellij_version not in system_base_zellij_cmd_output.stdout

- name: Verify if group exists
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - render
    - dialout
    - rgb

- name: Assign user to groups
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ item }}"
    append: true
  loop:
    - render
    - dialout
    - rgb

- name: Reset SSH connection to apply group changes
  ansible.builtin.meta: reset_connection

- name: Change default shell to Fish
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: "{{ system_base_shell }}"

- name: Upload custom Udev rules for ASRock RGB
  ansible.builtin.template:
    src: "asrock-rgb.rules.j2"
    dest: "/etc/udev/rules.d/99-asrock-rgb.rules"
    owner: root
    group: root
    mode: "0644"
  notify: Reload Udev rules
