---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "/srv/monitoring/grafana"
    - "/srv/monitoring/grafana/provisioning"
    - "/srv/monitoring/grafana/provisioning/datasources"
    - "/srv/monitoring/grafana/provisioning/dashboards"
    - "/srv/monitoring/grafana/provisioning/alerting"
    - "/srv/monitoring/grafana/provisioning/plugins"
    - "/srv/monitoring/grafana/data"

- name: Upload .network file
  ansible.builtin.template:
    src: "grafana.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/grafana.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Upload .env file
  ansible.builtin.template:
    src: "grafana.env.j2"
    dest: "/srv/monitoring/grafana/grafana.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  notify: Restart grafana

- name: Upload provisioning/datasources/datasources.yml file
  ansible.builtin.template:
    src: "datasources.yml.j2"
    dest: "/srv/monitoring/grafana/provisioning/datasources/datasources.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Upload provisioning/alerting/alerting.yml file
  ansible.builtin.template:
    src: "alerting.yml.j2"
    dest: "/srv/monitoring/grafana/provisioning/alerting/alerting.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Upload provisioning/alerting/contact-points.yml file
  ansible.builtin.template:
    src: "contact-points.yml.j2"
    dest: "/srv/monitoring/grafana/provisioning/alerting/contact-points.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Upload provisioning/dashboards/dashboards.yml file
  ansible.builtin.template:
    src: "dashboards.yml.j2"
    dest: "/srv/monitoring/grafana/provisioning/dashboards/dashboards.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Sync dashboard files
  ansible.posix.synchronize:
    src: "files/dashboards/"
    dest: "/srv/monitoring/grafana/provisioning/dashboards/"
    delete: true
    archive: true
    owner: false
    group: false
    rsync_opts:
      - "--exclude=dashboards.yml"
      - "--chmod=D0755,F0644"
      - "--chown={{ ansible_user }}:{{ ansible_user }}"

- name: Upload .container file
  ansible.builtin.template:
    src: "grafana.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/grafana.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart grafana

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ grafana_image }}:{{ version_grafana }}"
    state: present
