---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/srv/monitoring/grafana"
    - "/srv/monitoring/grafana/provisioning"
    - "/srv/monitoring/grafana/provisioning/datasources"
    - "/srv/monitoring/grafana/provisioning/dashboards"
    - "/srv/monitoring/grafana/data"

- name:  Upload .network file
  ansible.builtin.template:
    src: "grafana.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/grafana.network"
    mode: '0644'
  notify: Restart grafana

- name: Upload .env file
  ansible.builtin.template:
    src: "grafana.env.j2"
    dest: "/srv/monitoring/grafana/grafana.env"
    mode: '0600'
  no_log: true
  notify: Restart grafana

- name: Upload provisioning/datasources/datasources.yml file
  ansible.builtin.template:
    src: "datasources.yml.j2"
    dest: "/srv/monitoring/grafana/provisioning/datasources/datasources.yml"
    mode: '0644'
  notify: Restart grafana

- name: Upload provisioning/dashboards files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/srv/monitoring/grafana/provisioning/dashboards/{{ item }}"
    mode: '0644'
  loop:
    - "frigate-dashboard.json"
    - "podman-dashboard.json"
  notify: Restart grafana

- name: Upload .container file
  ansible.builtin.template:
    src: "grafana.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/grafana.container"
    mode: '0644'
  notify: Restart grafana

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ grafana_image }}"
    state: present
