---
- name: Ensure Logical Volumes exist and are sized correctly
  community.general.lvol:
    vg: "{{ storage_vg_name }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    resizefs: true
  loop: "{{ storage_target_lvs }}"

- name: Ensure XFS filesystem is formatted on required LVs
  community.general.filesystem:
    fstype: xfs
    dev: "/dev/{{ storage_vg_name }}/{{ item.name }}"
  loop: "{{ storage_target_lvs }}"
  when: item.manage_fs_and_mount | bool
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure required LVs are in fstab and mounted
  ansible.posix.mount:
    path: "{{ item.mount_path }}"
    src: "/dev/{{ storage_vg_name }}/{{ item.name }}"
    fstype: xfs
    state: mounted
  loop: "{{ storage_target_lvs }}"
  when: item.manage_fs_and_mount | bool

- name: Hand over /srv/monitoring to the rootless user
  ansible.builtin.file:
    path: /srv/monitoring
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Check if mountpoints exists
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop: "{{ storage_data_drives }}"

- name: Mount drives and add to fstab
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    dump: "0"
    passno: "{{ item.passno }}"
    opts: defaults,nofail
    state: mounted
  loop: "{{ storage_data_drives }}"

- name: Ensure correct permissions on mounted drives
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop: "{{ storage_data_drives }}"

- name: Create systemd drop-in directory for fstrim.timer
  ansible.builtin.file:
    path: "/etc/systemd/system/fstrim.timer.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Configure fstrim.timer override schedule
  ansible.builtin.template:
    src: "fstrim_override.conf.j2"
    dest: "/etc/systemd/system/fstrim.timer.d/override.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart fstrim timer
