# TODO: not sure if the "all" listeningMode is correct one here
pihole_dns_listening_mode: "all"
pihole_dns_rev_servers: "true,192.168.2.0/24,192.168.2.1;true,192.168.4.0/24,192.168.4.1"
pihole_session_timeout: 2592000

pihole_memory_limit: "500m"

# https://hub.docker.com/r/pihole/pihole
# https://github.com/pi-hole/docker-pi-hole
pihole_image: "docker.io/pihole/pihole"
