---
# TODO: not sure if the "all" listeningMode is correct one here
pihole_dns_listening_mode: "all"
pihole_dns_rev_servers: >-
  {{
    [
      'true,' ~ vault_network_home ~ ',' ~ vault_gateway_home,
      'true,' ~ vault_network_homelab ~ ',' ~ vault_gateway_homelab,
      'true,' ~ vault_network_iot ~ ',' ~ vault_gateway_iot
    ] | join(';')
  }}
pihole_session_timeout: 2592000
pihole_memory_limit: "1g"

# https://hub.docker.com/r/pihole/pihole
# https://github.com/pi-hole/docker-pi-hole
pihole_image: "docker.io/pihole/pihole"

# renovate: datasource=docker depName=docker.io/pihole/pihole
pihole_version: "2026.07.2"
