---
authelia_memory_limit: "500m"
authelia_redis_memory_limit: "500m"
authelia_postgres_memory_limit: "500m"

# https://hub.docker.com/r/authelia/authelia
authelia_image: "docker.io/authelia/authelia"

# https://hub.docker.com/_/redis
authelia_redis_image: "docker.io/library/redis"

# https://hub.docker.com/_/postgres
authelia_postgres_image: "docker.io/library/postgres"
