---
mosquitto_memory_limit: "500m"

# https://hub.docker.com/_/eclipse-mosquitto
mosquitto_image: "docker.io/library/eclipse-mosquitto"

# renovate: datasource=docker depName=docker.io/library/eclipse-mosquitto
mosquitto_version: "2.1.2-alpine"
