---
prometheus_memory_limit: "2g"

# https://hub.docker.com/r/prom/prometheus
prometheus_image: "docker.io/prom/prometheus"

# renovate: datasource=docker depName=docker.io/prom/prometheus
prometheus_version: "v3.14.0-distroless"
