---
immich_memory_limit: "6g"
immich_machine_learning_memory_limit: "6g"
immich_redis_memory_limit: "500m"
immich_postgres_memory_limit: "500m"

immich_storage_path: "/srv/immich"

# https://github.com/immich-app/immich
immich_image: "ghcr.io/immich-app/immich-server"

immich_machine_learning_image: "ghcr.io/immich-app/immich-machine-learning"

immich_redis_image: "docker.io/valkey/valkey"

immich_postgres_image: "ghcr.io/immich-app/postgres"
