---
system_base_masked_units:
  - bluetooth.service
  - passim.service
  - pcscd.socket
  - pcscd.service
  - abrtd.service
  - abrt-journal-core.service
  - abrt-oops.service
  - abrt-vmcore.service
  - abrt-xorg.service
  - sssd.service
  - sssd-kcm.service
  - sssd-kcm.socket
  - iscsid.socket
  - iscsid.service
  - iscsi.service
  - iscsiuio.socket
  - iscsi-onboot.service
  - multipathd.service
  - multipathd.socket
  # - plymouth-start.service
  # - plymouth-quit-wait.service
  - ModemManager.service
  - wpa_supplicant.service
  - avahi-daemon.socket
  - avahi-daemon.service
