---
- name: Verify if config directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  loop:
    # TODO permissions
    - path: "{{ user_home }}/tools"
      mode: "0755"

    - path: "{{ user_home }}/.config/fish"
      mode: "0700"

    - path: "{{ user_home }}/.config/fish/completions"
      mode: "0755"

    - path: "{{ user_home }}/.config/fastfetch"
      mode: "0744"

    - path: "{{ user_home }}/.config/zellij"
      mode: "0755"

    - path: "{{ user_home }}/.config/zellij/layouts"
      mode: "0755"

    - path: "{{ stacks_path }}"
      mode: "0755"

    - path: "{{ user_bin_path }}"
      mode: "0700"

- name: Upload Fish config
  ansible.builtin.copy:
    src: "fish/config.fish"
    dest: "{{ user_home }}/.config/fish/config.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Generate Zellij completions for Fish
  ansible.builtin.shell: zellij setup --generate-completion fish > {{ user_home }}/.config/fish/completions/zellij.fish
  args:
    creates: "{{ user_home }}/.config/fish/completions/zellij.fish"

- name: Upload Fastfetch config
  ansible.builtin.copy:
    src: "fastfetch/config.jsonc"
    dest: "{{ user_home }}/.config/fastfetch/config.jsonc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Upload Zellij config
  ansible.builtin.copy:
    src: "zellij/config.kdl"
    dest: "{{ user_home }}/.config/zellij/config.kdl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Upload Zellij layout
  ansible.builtin.copy:
    src: "zellij/default_strider.kdl"
    dest: "{{ user_home }}/.config/zellij/layouts/default_strider.kdl"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
