---
- name: Verify if config directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ item.mode }}"
  loop:
    # TODO permissions
    - path: "/home/{{ ansible_user }}/tools"
      mode: "0755"

    - path: "/home/{{ ansible_user }}/.config/fish"
      mode: "0700"

    - path: "/home/{{ ansible_user }}/.config/fastfetch"
      mode: "0744"

    - path: "{{ stacks_path }}"
      mode: "0755"

    - path: "/home/{{ ansible_user }}/.local/bin"
      mode: "0700"

- name: Upload Fish config
  ansible.builtin.copy:
    src: "fish/config.fish"
    dest: "/home/{{ ansible_user }}/.config/fish/config.fish"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Upload Fastfetch config
  ansible.builtin.copy:
    src: "fastfetch/config.jsonc"
    dest: "/home/{{ ansible_user }}/.config/fastfetch/config.jsonc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
