---
- name: Orion rootless services
  hosts: orion
  become: false
  environment: "{{ podman_user_env }}"
  roles:
    # =====================================================
    # Services (Rootless)
    # =====================================================
    - role: eink_display
      tags: ["eink_display"]
