---
- name: Create directory for systemd-resolved configs
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Disable DNSStubListener (free port 53)
  ansible.builtin.template:
    src: pihole.conf.j2
    dest: /etc/systemd/resolved.conf.d/pihole.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart systemd-resolved

# Default: ../run/systemd/resolve/stub-resolv.conf
- name: Update /etc/resolv.conf symlink (bypass stub)
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Set host to use local Pi-hole with Quad9 fallback
  community.general.nmcli:
    conn_name: "{{ primary_network_interface_name }}"
    ifname: "{{ primary_network_interface_name }}"
    type: ethernet
    dns4:
      - "127.0.0.1"
      - "9.9.9.11"
      - "149.112.112.11"
    dns4_ignore_auto: true
    state: present
    conn_reload: true
  notify: Apply primary network interface changes
