---
- name: Create directory for systemd-resolved configs
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Disable DNSStubListener (free port 53)
  ansible.builtin.template:
    src: pihole.conf.j2
    dest: /etc/systemd/resolved.conf.d/pihole.conf
    owner: root
    group: root
    mode: "0644"
  register: network_stub_disabled

# Default: ../run/systemd/resolve/stub-resolv.conf
- name: Update /etc/resolv.conf symlink (bypass stub)
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: restarted
  when: network_stub_disabled.changed # noqa: no-handler

- name: Verify that port 53 is free
  ansible.builtin.wait_for:
    port: 53
    state: stopped
    host: 127.0.0.1
    timeout: 10
  ignore_errors: "{{ ansible_check_mode }}"
  when: network_stub_disabled.changed # noqa: no-handler

- name: Set host to use local Pi-hole with Quad9 fallback
  community.general.nmcli:
    conn_name: "{{ primary_network_interface_name }}"
    ifname: "{{ primary_network_interface_name }}"
    type: ethernet
    dns4:
      - "127.0.0.1"
      - "9.9.9.11"
      - "149.112.112.11"
    dns4_ignore_auto: true
    state: present
    conn_reload: true
  register: network_local_dns_result

- name: Apply local DNS connection changes
  community.general.nmcli:
    conn_name: "{{ primary_network_interface_name }}"
    ifname: "{{ primary_network_interface_name }}"
    state: up
  when: network_local_dns_result.changed # noqa: no-handler
