---
- name: Create host-only service interface for containers
  community.general.nmcli:
    conn_name: podhost
    ifname: podhost
    type: dummy
    ip4: "{{ host_svc_address }}/32"
    method6: disabled
    zone: trusted
    autoconnect: true
    may_fail4: false
    state: present
