---
- name: Configure Kernel Parameters
  ansible.builtin.include_tasks: sysctl.yml

- name: Configure Network Interfaces and Features
  ansible.builtin.include_tasks: network.yml

- name: Configure dummy Podman Interface
  ansible.builtin.include_tasks: hostnet.yml

- name: Configure Host DNS and systemd-resolved
  ansible.builtin.include_tasks: dns.yml

- name: Configure Core Services (NTP, Cockpit)
  ansible.builtin.include_tasks: services.yml

- name: Flush handlers to apply OS network and service changes
  ansible.builtin.meta: flush_handlers

- name: Ensure OS level services are started and enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - systemd-resolved.service
    - chronyd.service
    - cockpit.socket
  ignore_errors: "{{ ansible_check_mode }}"
