---
- name: Let users set services on ports 53+
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: '53'
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable IPv4 and IPv6 forwarding for routing
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding

- name: Check current primary interface ethtool UDP GRO settings
  ansible.builtin.command: "nmcli -g ethtool.feature-rx-udp-gro-forwarding connection show '{{ primary_network_interface_name }}'"
  register: primary_current_gro
  changed_when: false
  check_mode: false

- name: Modify primary interface connection to enable UDP GRO offloading
  ansible.builtin.command: >
    nmcli connection modify "{{ primary_network_interface_name }}" 
    ethtool.feature-rx-udp-gro-forwarding on 
    ethtool.feature-rx-gro-list off
  when: "'on' not in primary_current_gro.stdout"
  register: primary_gro_modify

- name: Check current secondary interface ethtool UDP GRO settings
  ansible.builtin.command: "nmcli -g ethtool.feature-rx-udp-gro-forwarding connection show '{{ secondary_network_interface_name }}'"
  register: secondary_current_gro
  changed_when: false
  check_mode: false

- name: Modify secondary interface connection to enable UDP GRO offloading
  ansible.builtin.command: >
    nmcli connection modify "{{ secondary_network_interface_name }}" 
    ethtool.feature-rx-udp-gro-forwarding on 
    ethtool.feature-rx-gro-list off
  when: "'on' not in secondary_current_gro.stdout"
  register: secondary_gro_modify

# Default: #allow 192.168.0.0/16
- name: Allow NTP queries for selected subnet
  ansible.builtin.lineinfile:
    path: "/etc/chrony.conf"
    regexp: '^#?allow\s+'
    line: "allow {{ network_cctv }}"
    state: present
  notify: Restart chronyd

- name: Enable cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"

# firewall-cmd --get-services (list of available services)
- name: Open required ports
  ansible.posix.firewalld:
    service: "{{ item.service | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - { service: "cockpit" } # TODO: remove when caddy will work as a proxy to cockpit
    - { service: "ntp" }
    - { service: "dns" }
    - { service: "http" }
    - { service: "https" }
    - { port: "8555/tcp" }
    - { port: "8555/udp "}
    - { service: "nut" }
    - { service: "ssh" }
    - { service: "dhcpv6-client" }
    - { port: "443/udp" }
    - { port: "41641/udp" }

- name: Remove the default connection
  community.general.nmcli:
    conn_name: "Wired connection 1"
    state: absent
  ignore_errors: true

- name: Configure second isolated network interface
  community.general.nmcli:
    conn_name: "{{ secondary_network_interface_name }}"
    ifname: "{{ secondary_network_interface_name }}"
    type: ethernet
    ip4: "{{ secondary_ip }}/24"
    method4: manual
    state: present
    conn_reload: true
  register: secondary_network_interface

- name: Apply primary network interface changes
  community.general.nmcli:
    conn_name: "{{ primary_network_interface_name }}"
    ifname: "{{ primary_network_interface_name }}"
    state: up
  when: primary_gro_modify.changed

- name: Apply secondary network interface changes
  community.general.nmcli:
    conn_name: "{{ secondary_network_interface_name }}"
    ifname: "{{ secondary_network_interface_name }}"
    state: up
  when: secondary_network_interface.changed or secondary_gro_modify.changed

- name: Check Wi-Fi status
  ansible.builtin.command: nmcli radio wifi
  register: wifi_status
  changed_when: false
  check_mode: false

- name: Disable Wi-Fi
  ansible.builtin.command: nmcli radio wifi off
  when: "'enabled' in wifi_status.stdout"

- name: Configure fail2ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      banaction = firewallcmd-rich-rules
      bantime  = 1h
      findtime  = 10m
      maxretry = 3

      [sshd]
      enabled = true
      mode    = normal
    mode: '0644'
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban.service
    state: started
    enabled: yes
