---
- name: Configure Kernel Parameters
  ansible.builtin.include_tasks: sysctl.yml

- name: Configure Network Interfaces and Features
  ansible.builtin.include_tasks: network.yml

- name: Configure Core Services (NTP, Cockpit)
  ansible.builtin.include_tasks: services.yml
