---
- name: Check current primary interface ethtool UDP GRO settings
  ansible.builtin.command: "nmcli -g ethtool.feature-rx-udp-gro-forwarding connection show '{{ primary_network_interface_name }}'"
  register: network_primary_current_gro
  changed_when: false
  check_mode: false

- name: Modify primary interface connection to enable UDP GRO offloading
  ansible.builtin.command: >
    nmcli connection modify "{{ primary_network_interface_name }}"
    ethtool.feature-rx-udp-gro-forwarding on
    ethtool.feature-rx-gro-list off
  when: "'on' not in network_primary_current_gro.stdout"
  changed_when: true
  notify: Apply primary network interface changes

- name: Check current secondary interface ethtool UDP GRO settings
  ansible.builtin.command: "nmcli -g ethtool.feature-rx-udp-gro-forwarding connection show '{{ secondary_network_interface_name }}'"
  register: network_secondary_current_gro
  changed_when: false
  check_mode: false

- name: Modify secondary interface connection to enable UDP GRO offloading
  ansible.builtin.command: >
    nmcli connection modify "{{ secondary_network_interface_name }}"
    ethtool.feature-rx-udp-gro-forwarding on
    ethtool.feature-rx-gro-list off
  when: "'on' not in network_secondary_current_gro.stdout"
  changed_when: true
  notify: Apply secondary network interface changes

- name: Remove the default connection
  community.general.nmcli:
    conn_name: "Wired connection 1"
    state: absent

- name: Configure second isolated network interface
  community.general.nmcli:
    conn_name: "{{ secondary_network_interface_name }}"
    ifname: "{{ secondary_network_interface_name }}"
    type: ethernet
    ip4: "{{ vault_secondary_ip }}/24"
    method4: manual
    state: present
    conn_reload: true
  notify: Apply secondary network interface changes

- name: Check Wi-Fi status
  ansible.builtin.command: nmcli radio wifi
  register: network_wifi_status
  changed_when: false
  check_mode: false

- name: Disable Wi-Fi
  ansible.builtin.command: nmcli radio wifi off
  when: "'enabled' in network_wifi_status.stdout"
  changed_when: true
