---
# Default: #allow 192.168.0.0/16
- name: Allow NTP queries for selected subnet
  ansible.builtin.lineinfile:
    path: "/etc/chrony.conf"
    regexp: '^#?allow\s+'
    line: "allow {{ network_cctv }}"
    state: present
  notify: Restart chronyd

- name: Enable cockpit.socket
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
    state: started
  ignore_errors: "{{ ansible_check_mode }}"

- name: Configure fail2ban
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban.service
    state: started
    enabled: true
