---
- name: Load tcp_bbr module and make it persistent
  community.general.modprobe:
    name: tcp_bbr
    state: present
    persistent: present

- name: Configure system-wide network and kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-homelab-network.conf
  loop:
    - { name: "net.ipv4.ip_unprivileged_port_start", value: "53" }
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }

    - { name: "net.core.default_qdisc", value: "fq" }
    - { name: "net.ipv4.tcp_congestion_control", value: "bbr" }
