---
- name: Deploy Frigate
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: frigate
    podman_service_dirs:
      - "{{ stacks_path }}/frigate"
      - "{{ stacks_path }}/frigate/config"
      - "{{ stacks_path }}/frigate/nginx"
      - "{{ frigate_storage_path }}"
      - "{{ frigate_storage_path }}/recordings"
      - "{{ frigate_storage_path }}/clips"
      - "{{ frigate_storage_path }}/exports"
    podman_service_templates:
      - src: frigate.env.j2
        dest: "{{ stacks_path }}/frigate/frigate.env"
        mode: "0600"
        no_log: true
      - src: config.yaml.j2
        dest: "{{ stacks_path }}/frigate/config/config.yaml"
        mode: "0644"
      - src: nginx.conf.j2
        dest: "{{ stacks_path }}/frigate/nginx/nginx.conf"
        mode: "0644"
    podman_service_quadlets: ["frigate.container"]
    podman_service_images: ["{{ frigate_image }}:{{ frigate_version }}"]
