---
zigbee2mqtt_memory_limit: "1g"

# https://github.com/Koenkk/zigbee2mqtt
zigbee2mqtt_image: "ghcr.io/koenkk/zigbee2mqtt"

zigbee2mqtt_channel: 11
zigbee2mqtt_adapter: "ember"

# renovate: datasource=pypi depName=universal-silabs-flasher
zigbee2mqtt_silabs_flasher_version: "1.1.0"

# renovate: datasource=docker depName=ghcr.io/koenkk/zigbee2mqtt
zigbee2mqtt_version: "2.13.0"
