---
backup_rclone_remote_name: "external"
backup_rclone_target: "{{ backup_rclone_remote_name }}:{{ vault_backup_rclone_bucket_name }}"

backup_restic_password_file: "{{ user_config_path }}/restic/.repo_pass"

backup_b2_quota_bytes: 9000000000
