---
- name: Deploy Immich
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: immich
    podman_service_dirs:
      - "{{ stacks_path }}/immich"
      - "{{ stacks_path }}/immich/model-cache"
      - "{{ stacks_path }}/immich/secrets"
      - "{{ stacks_path }}/immich/postgres"
      - "{{ immich_storage_path }}"
      - "{{ immich_storage_path }}/data"
    podman_service_secrets:
      - content: "{{ vault_immich_storage_password }}"
        dest: "{{ stacks_path }}/immich/secrets/STORAGE_PASSWORD"
    podman_service_templates:
      - src: immich-config.json.j2
        dest: "{{ stacks_path }}/immich/immich-config.json"
        mode: "0644"
      - src: immich.env.j2
        dest: "{{ stacks_path }}/immich/immich.env"
        mode: "0600"
        no_log: true
      - src: immich-machine-learning.env.j2
        dest: "{{ stacks_path }}/immich/immich-machine-learning.env"
        mode: "0600"
        no_log: true
    podman_service_quadlets:
      - immich-postgres.container
      - immich-redis.container
      - immich-machine-learning.container
      - immich.container
    podman_service_images:
      - "{{ immich_postgres_image }}:{{ immich_postgres_version }}"
      - "{{ immich_redis_image }}:{{ immich_redis_version }}"
      - "{{ immich_machine_learning_image }}:{{ immich_machine_learning_version }}"
      - "{{ immich_image }}:{{ immich_version }}"
