---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/immich"
    - "{{ stacks_path }}/immich/model-cache"
    - "{{ stacks_path }}/immich/secrets"
    - "{{ stacks_path }}/immich/postgres"
    - "{{ immich_storage_path }}"
    - "{{ immich_storage_path }}/data"

- name: Resolve render GID
  ansible.builtin.getent:
    database: group
    key: render

- name: Upload secret files
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ stacks_path }}/immich/secrets/{{ item.name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  loop:
    - name: "STORAGE_PASSWORD"
      value: "{{ vault_immich_storage_password }}"
  no_log: true
  notify:
    - Restart immich
    - Restart immich-postgres

- name: Upload immich-config.json file
  ansible.builtin.template:
    src: "immich-config.json.j2"
    dest: "{{ stacks_path }}/immich/immich-config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart immich

- name: Upload .env files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ stacks_path }}/immich/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  loop:
    - immich.env
    - immich-machine-learning.env
  notify:
    - Restart immich
    - Restart immich-machine-learning

- name: Upload .network files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ quadlet_path }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - immich.network
    - immich-backend.network
  notify:
    - Restart immich
    - Restart immich-machine-learning
    - Restart immich-postgres
    - Restart immich-redis

- name: Upload Immich .container file
  ansible.builtin.template:
    src: "immich.container.j2"
    dest: "{{ quadlet_path }}/immich.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart immich

- name: Upload Immich Machine Learning .container file
  ansible.builtin.template:
    src: "immich-machine-learning.container.j2"
    dest: "{{ quadlet_path }}/immich-machine-learning.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart immich-machine-learning

- name: Upload Postgres and Redis .container files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ quadlet_path }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - immich-postgres.container
    - immich-redis.container
  notify:
    - Restart immich-postgres
    - Restart immich-redis

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ immich_image }}:{{ immich_version }}"
    - "{{ immich_machine_learning_image }}:{{ immich_machine_learning_version }}"
    - "{{ immich_redis_image }}:{{ immich_redis_version }}"
    - "{{ immich_postgres_image }}:{{ immich_postgres_version }}"

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ item }}.service"
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  loop:
    - immich-postgres
    - immich-redis
    - immich-machine-learning
    - immich
  ignore_errors: "{{ ansible_check_mode }}"
