---
- name: Deploy Prometheus
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: prometheus
    podman_service_dirs:
      - "{{ monitoring_path }}/prometheus"
      - "{{ monitoring_path }}/prometheus/data"
    podman_service_templates:
      - src: prometheus.yml.j2
        dest: "{{ monitoring_path }}/prometheus/prometheus.yml"
        mode: "0644"
    podman_service_quadlets: ["prometheus.container"]
    podman_service_images: ["{{ prometheus_image }}:{{ prometheus_version }}"]
