---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/zigbee2mqtt"
    - "{{ stacks_path }}/zigbee2mqtt/data"
    - "{{ stacks_path }}/zigbee2mqtt/config"

- name: Upload .env file
  ansible.builtin.template:
    src: "zigbee2mqtt.env.j2"
    dest: "{{ stacks_path }}/zigbee2mqtt/zigbee2mqtt.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  notify: Restart zigbee2mqtt

- name: Upload configuration.yaml file
  ansible.builtin.template:
    src: "configuration.yaml.j2"
    dest: "{{ stacks_path }}/zigbee2mqtt/config/configuration.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart zigbee2mqtt

- name: Seed devices.yaml and groups.yaml files (do not overwrite)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ stacks_path }}/zigbee2mqtt/config/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    force: false
  loop:
    - "devices.yaml"
    - "groups.yaml"
  notify: Restart zigbee2mqtt

- name: Upload secret.yaml file
  ansible.builtin.template:
    src: "secret.yaml.j2"
    dest: "{{ stacks_path }}/zigbee2mqtt/config/secret.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  notify: Restart zigbee2mqtt

- name: Upload .container file
  ansible.builtin.template:
    src: "zigbee2mqtt.container.j2"
    dest: "{{ quadlet_path }}/zigbee2mqtt.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart zigbee2mqtt

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ zigbee2mqtt_image }}:{{ zigbee2mqtt_version }}"
    state: present

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: zigbee2mqtt.service
    state: started
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create directory for the Silabs Flasher tool
  ansible.builtin.file:
    path: "{{ user_tools_path }}/universal-silabs-flasher"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

# https://github.com/NabuCasa/universal-silabs-flasher
- name: Install universal-silabs-flasher inside a Python virtual environment
  ansible.builtin.pip:
    name: "universal-silabs-flasher=={{ zigbee2mqtt_silabs_flasher_version }}"
    virtualenv: "{{ user_tools_path }}/universal-silabs-flasher/venv"
    virtualenv_command: "python3 -m venv"
    state: present
