---
- name: Deploy Zigbee2MQTT
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: zigbee2mqtt
    podman_service_dirs:
      - "{{ stacks_path }}/zigbee2mqtt"
      - "{{ stacks_path }}/zigbee2mqtt/data"
      - "{{ stacks_path }}/zigbee2mqtt/config"
    podman_service_templates:
      - src: configuration.yaml.j2
        dest: "{{ stacks_path }}/zigbee2mqtt/config/configuration.yaml"
        mode: "0644"
      - src: devices.yaml.j2
        dest: "{{ stacks_path }}/zigbee2mqtt/config/devices.yaml"
        mode: "0644"
        force: false
      - src: groups.yaml.j2
        dest: "{{ stacks_path }}/zigbee2mqtt/config/groups.yaml"
        mode: "0644"
        force: false
      - src: secret.yaml.j2
        dest: "{{ stacks_path }}/zigbee2mqtt/config/secret.yaml"
        mode: "0600"
        no_log: true
    podman_service_quadlets: ["zigbee2mqtt.container"]
    podman_service_images: ["{{ zigbee2mqtt_image }}:{{ zigbee2mqtt_version }}"]

# https://github.com/NabuCasa/universal-silabs-flasher
- name: Install universal-silabs-flasher inside a Python virtual environment
  ansible.builtin.pip:
    name: "universal-silabs-flasher=={{ zigbee2mqtt_silabs_flasher_version }}"
    virtualenv: "{{ user_tools_path }}/universal-silabs-flasher/venv"
    virtualenv_command: "python3 -m venv"
    state: present
