---
eink_display_repo: "https://github.com/Zireaell1/nova-eink-display.git"

# renovate: datasource=pypi depName=eink-display-uv packageName=uv
eink_display_uv_version: "0.12.17"

eink_display_path: "{{ user_home }}/eink-display"
