---
eink_display_repo: "https://github.com/Zireaell1/nova-eink-display.git"

# renovate: datasource=pypi depName=uv
eink_display_uv_version: "0.12.7"

eink_display_path: "{{ user_home }}/eink-display"
