---
- name: Deploy Systemd Service file
  ansible.builtin.template:
    src: "podman-prune.service.j2"
    dest: "/home/{{ ansible_user }}/.config/systemd/user/podman-prune.service"
    mode: "0644"

- name: Deploy Systemd Timer file
  ansible.builtin.template:
    src: "podman-prune.timer.j2"
    dest: "/home/{{ ansible_user }}/.config/systemd/user/podman-prune.timer"
    mode: "0644"

- name: Enable and start the Timer
  ansible.builtin.systemd:
    name: podman-prune.timer
    scope: user
    enabled: true
    state: started
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
