---
- name: Nova Homelab configuration
  hosts: nova
  become: false
  roles:
    - role: base
      become: true
      tags: ["base"]

    - role: storage
      become: true
      tags: ["storage"]
    - role: users
      become: true
      tags: ["users"]
    - role: network
      become: true
      tags: ["network"]
    - role: nut
      become: true
      tags: ["nut"]

    - role: openrgb
      tags: ["openrgb"]

    - role: monitoring_base
      tags: ["monitoring_base", "monitoring"]
    - role: prometheus
      tags: ["prometheus", "monitoring"]
    - role: loki
      tags: ["loki", "monitoring"]
    - role: alloy
      become: true
      tags: ["alloy", "monitoring"]
    - role: grafana
      tags: ["grafana", "monitoring"]

    - role: pihole
      tags: ["pihole"]
    - role: authelia
      tags: ["authelia"]
    - role: mosquitto
      tags: ["mosquitto", "home"]
    - role: restic
      tags: ["restic"]
    - role: frigate
      tags: ["frigate", "home"]
    - role: vaultwarden
      tags: ["vaultwarden"]
    - role: zigbee2mqtt
      tags: ["zigbee2mqtt", "home"]
    - role: peanut
      tags: ["peanut"]
    - role: immich
      tags: ["immich"]
    - role: homeassistant
      tags: ["homeassistant"]

    - role: caddy
      tags: ["caddy"]

    - role: podman
      tags: ["podman"]

    - role: backup
      tags: ["backup"]

    - role: tailscale
      become: true
      tags: ["tailscale"]

- name: Orion RPI configuration
  hosts: orion
  become: false
  roles:
    - role: rpi_base
      become: true
      tags: ["rpi_base"]
    - role: eink_display
      tags: ["eink_display"]
