---
- name: Software install
  ansible.builtin.dnf:
    name:
      - fail2ban
    state: present

- name: Ensure sshd_config.d directory exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Configure SSH hardening (disable password auth)
  ansible.builtin.template:
    src: 40-hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/40-hardening.conf
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/sshd -t -f %s
  notify: Reload sshd

- name: Ensure filter.d directory exists
  ansible.builtin.file:
    path: /etc/fail2ban/filter.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Vaultwarden filter
  ansible.builtin.template:
    src: vaultwarden.local.j2
    dest: /etc/fail2ban/filter.d/vaultwarden.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Configure jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Define SELinux policy for Frigate directory
  community.general.sefcontext:
    target: "{{ frigate_mount }}/storage(/.*)?"
    setype: container_file_t
    state: present
  notify: Apply Frigate SELinux policy

- name: Flush handlers to apply system changes
  ansible.builtin.meta: flush_handlers

- name: Ensure core OS services are enabled and running
  ansible.builtin.service:
    name: "{{ item }}.service"
    state: started
    enabled: true
  loop:
    - sshd
    - fail2ban
  ignore_errors: "{{ ansible_check_mode }}"
