---
- name: Software install
  ansible.builtin.dnf:
    name:
      - fail2ban
    state: present

- name: Ensure filter.d directory exists
  ansible.builtin.file:
    path: /etc/fail2ban/filter.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Vaultwarden filter
  ansible.builtin.template:
    src: vaultwarden.local.j2
    dest: /etc/fail2ban/filter.d/vaultwarden.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Configure jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban

- name: Flush handlers to apply system changes
  ansible.builtin.meta: flush_handlers

- name: Ensure core OS services are enabled and running
  ansible.builtin.service:
    name: "fail2ban.service"
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
