---
- name: Deploy Authelia
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: authelia
    podman_service_dirs:
      - "{{ stacks_path }}/authelia"
      - "{{ stacks_path }}/authelia/config"
      - "{{ stacks_path }}/authelia/secrets"
      - "{{ stacks_path }}/authelia/postgres"
      - "{{ stacks_path }}/authelia/redis"
    podman_service_templates:
      - src: configuration.yml.j2
        dest: "{{ stacks_path }}/authelia/config/configuration.yml"
        mode: "0644"
      - src: authelia.env.j2
        dest: "{{ stacks_path }}/authelia/authelia.env"
        mode: "0600"
    podman_service_secrets:
      - content: "{{ vault_authelia_hmac_secret }}"
        dest: "{{ stacks_path }}/authelia/secrets/HMAC_SECRET"
      - content: "{{ vault_authelia_jwt_secret }}"
        dest: "{{ stacks_path }}/authelia/secrets/JWT_SECRET"
      - content: "{{ vault_authelia_redis_password }}"
        dest: "{{ stacks_path }}/authelia/secrets/REDIS_PASSWORD"
      - content: "{{ vault_authelia_session_secret }}"
        dest: "{{ stacks_path }}/authelia/secrets/SESSION_SECRET"
      - content: "{{ vault_authelia_storage_encryption_key }}"
        dest: "{{ stacks_path }}/authelia/secrets/STORAGE_ENCRYPTION_KEY"
      - content: "{{ vault_authelia_storage_password }}"
        dest: "{{ stacks_path }}/authelia/secrets/STORAGE_PASSWORD"
      - content: "{{ vault_authelia_rsa2048 }}"
        dest: "{{ stacks_path }}/authelia/secrets/rsa.2048.key"
      - content: "{{ vault_authelia_users_database }}"
        dest: "{{ stacks_path }}/authelia/config/users_database.yml"
    podman_service_quadlets:
      - authelia-postgres
      - authelia-redis
      - authelia
    podman_service_images:
      - "{{ authelia_image }}:{{ authelia_version }}"
      - "{{ authelia_redis_image }}:{{ authelia_redis_version }}"
      - "{{ authelia_postgres_image }}:{{ authelia_postgres_version }}"
