---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ restic_data_path }}"

- name: Upload .network file
  ansible.builtin.template:
    src: "restic.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/restic.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart restic

- name: Upload .container file
  ansible.builtin.template:
    src: "restic.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/restic.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart restic

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ restic_image }}:{{ version_restic }}"
    state: present
