---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ restic_data_path }}"

- name: Upload .network file
  ansible.builtin.template:
    src: "restic.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/restic.network"
    mode: '0644'
  notify: Restart restic

- name: Upload .container file
  ansible.builtin.template:
    src: "restic.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/restic.container"
    mode: '0644'
  notify: Restart restic

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ restic_image }}"
    state: present
