---
- name: Deploy Restic
  ansible.builtin.include_role:
    name: podman_service
  vars:
    podman_service_name: restic
    podman_service_dirs: ["{{ restic_server_path }}"]
    podman_service_quadlets: ["restic.container"]
    podman_service_images: ["{{ restic_image }}:{{ restic_version }}"]
