---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/caddy"
    - "{{ stacks_path }}/caddy/data"
    - "{{ stacks_path }}/caddy/config"
    - "{{ stacks_path }}/caddy/srv"
    - "{{ stacks_path }}/caddy/caddy-build"

- name: Copy files to /srv
  ansible.builtin.copy:
    src: "srv/{{ item }}"
    dest: "{{ stacks_path }}/caddy/srv/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - "windows-device-critical-backup.cmd"

- name: Upload .env file
  ansible.builtin.template:
    src: "caddy.env.j2"
    dest: "{{ stacks_path }}/caddy/caddy.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  notify: Restart caddy

- name: Upload Caddyfile
  ansible.builtin.template:
    src: "Caddyfile.j2"
    dest: "{{ stacks_path }}/caddy/Caddyfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart caddy
  # TODO: Reload caddy

- name: Upload Containerfile
  ansible.builtin.template:
    src: "Containerfile.j2"
    dest: "{{ stacks_path }}/caddy/caddy-build/Containerfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  register: caddy_containerfile

- name: Build image with Cloudflare plugin
  containers.podman.podman_image:
    name: custom-caddy
    tag: "{{ caddy_version }}"
    path: "{{ stacks_path }}/caddy/caddy-build"
    force: "{{ caddy_containerfile.changed }}"
  notify: Restart caddy

- name: Upload .socket file
  ansible.builtin.template:
    src: "caddy.socket.j2"
    dest: "{{ user_units_path }}/caddy.socket"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart caddy

- name: Upload .container file
  ansible.builtin.template:
    src: "caddy.container.j2"
    dest: "{{ quadlet_path }}/caddy.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart caddy

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: caddy.service
    state: started
    enabled: true
    scope: user
  ignore_errors: "{{ ansible_check_mode }}"
