---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stacks_path }}/mosquitto"
    - "{{ stacks_path }}/mosquitto/config"
    - "{{ stacks_path }}/mosquitto/data"
    - "{{ stacks_path }}/mosquitto/log"

- name: Upload pwfile file
  ansible.builtin.copy:
    content: "{{ vault_mosquitto_pwfile_content }}"
    dest: "{{ stacks_path }}/mosquitto/config/pwfile"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
  no_log: true
  notify: Restart mosquitto

- name: Upload mosquitto.conf file
  ansible.builtin.template:
    src: "mosquitto.conf.j2"
    dest: "{{ stacks_path }}/mosquitto/config/mosquitto.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart mosquitto

- name: Upload .container file
  ansible.builtin.template:
    src: "mosquitto.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/mosquitto.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart mosquitto

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ mosquitto_image }}:{{ mosquitto_version }}"
    state: present

- name: Flush handlers to restart stack if configurations changed
  ansible.builtin.meta: flush_handlers

- name: Ensure stack is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: mosquitto.service
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  ignore_errors: "{{ ansible_check_mode }}"
