---
frigate_memory_limit: "6g"

# https://github.com/blakeblackshear/frigate
frigate_image: "ghcr.io/blakeblackshear/frigate"

# renovate: datasource=docker depName=ghcr.io/blakeblackshear/frigate
frigate_version: "0.18.0-rc2"
