---
- name: Verify directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "/srv/monitoring/loki"
    - "/srv/monitoring/loki/data"

- name: Upload loki.yaml file
  ansible.builtin.template:
    src: "loki.yaml.j2"
    dest: "/srv/monitoring/loki/loki.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart loki

- name: Upload .network file
  ansible.builtin.template:
    src: "loki.network.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/loki.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart loki

- name: Upload .container file
  ansible.builtin.template:
    src: "loki.container.j2"
    dest: "/home/{{ ansible_user }}/.config/containers/systemd/loki.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart loki

- name: Download Podman images
  containers.podman.podman_image:
    name: "{{ loki_image }}:{{ version_loki }}"
    state: present
