---
name: Ansible Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Mock Vault and Passphrase File
        run: |
          cp examples/vault.yml.example ansible/group_vars/all/vault.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26
        with:
          working_directory: "ansible"
          requirements_file: "requirements.yml"
        env:
          ANSIBLE_CONFIG: "ansible-ci.cfg"
